[package]
name = "mdcat"
description = "cat for markdown: Show markdown documents in terminals"
readme = "README.md"
homepage = "https://github.com/lunaryorn/mdcat"
repository = "https://github.com/lunaryorn/mdcat"
documentation = "https://docs.rs/mdcat"
keywords = ["markdown", "less", "cat"]
version = "0.14.0"
categories = ["command-line-utilities", "text-processing"]
license = "Apache-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"

[features]
default = ["reqwest"]

[dependencies]
ansi_term = "^0.12"
base64 = "^0.11"
failure = "^0.1"
gethostname = "^0.2"
image = "^0.22.2"
mime = "^0.3"
term_size = "^0.3"
url = "^2.1"

# Dependency for reqwest which lets Kitty, iTerm2 and perhaps others
# fetch images from HTTP(S) URLs for display.  Without reqwest we use curl to
# fetch resources.
[dependencies.reqwest]
version = "^0.10"
optional = true
features = ["gzip", "blocking"]

[dependencies.clap]
version = "^2.33"
default-features = false
features = ["color", "wrap_help"]

[dependencies.pulldown-cmark]
version = "^0.6"
default-features = false
features = ['simd']

[dependencies.syntect]
# onig rust fails to build w/o clang currently so pin syntect,
# see <https://github.com/rust-onig/rust-onig/issues/109> and GH-90
version = "^3, <3.2"
default-features = false
features = ["parsing", "assets", "dump-load"]

[dev-dependencies]
pretty_assertions = "^0.6"

[profile.release]
# Enable LTO for release builds; makes the binary a lot smaller
lto = true
