[package]
name = "mdcat"
description = "cat for markdown: Show markdown documents in terminals"
readme = "README.md"
homepage = "https://github.com/lunaryorn/mdcat"
repository = "https://github.com/lunaryorn/mdcat"
documentation = "https://docs.rs/mdcat"
keywords = ["markdown", "less", "cat"]
version = "0.22.2"
categories = ["command-line-utilities", "text-processing"]
license = "MPL-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"

[features]
default = ["ureq"]

[dependencies]
ansi_term = "^0.12"
base64 = "^0.13"
gethostname = "^0.2"
image = "^0.23"
mime = "^0.3"
url = "^2.2"
fehler = "^1"
anyhow = "^1"
shell-words = "^1"
env_proxy = "^0.4"

[dependencies.clap]
version = "^2.33"
default-features = false

[dependencies.pulldown-cmark]
version = "^0.8"
default-features = false
features = ['simd']

[dependencies.syntect]
version = "^4.5"
default-features = false
features = ["parsing", "assets", "dump-load", "regex-fancy"]

[dependencies.ureq]
version = "^1.5"
optional = true
features = ["tls", "native-certs"]

[target.'cfg(unix)'.dependencies]
libc = "^0.2"

[target.'cfg(windows)'.dependencies]
terminal_size = "^0.1"

[dev-dependencies]
pretty_assertions = "^0.6"
goldenfile = "^1.1"
lazy_static = "^1.4"
test-generator = "^0.3"

[build-dependencies]
# To generate completions during build
clap = { version = "^2.33", default-features = false }

[profile.release]
# Enable LTO for release builds; makes the binary a lot smaller
lto = true
